### ISSUE TITLE
not supported resolving ES modules 

### ISSUE THREAD

**Issue by KoljaL** [perfect-things/ui#20]
I get the following error on a fresh SvelteKit installation.

- no TS
- no JSDoc

`Directory import '/Users/kolja/Code/pui-test/node_modules/@perfectthings/ui/src/autocomplete' is not supported resolving ES modules imported from /Users/lasarkolja/Code/pui-test/node_modules/@perfectthings/ui/src/index.js`

What can i do?

Thanks for this lib, it looks awesome :-)

**Comment by tborychowski** [comment]
Thanks for the report. I will look into this.
It would be helpful if you had a demo repo (even the skeleton, that I can clone and quickly see these errors).
If not I'd just use the default whatever they have now in SvelteKit.

**Comment by tborychowski** [comment]
OK. I made a small update to the imports and released a new version that's now consumable by SvelteKit apps (v6.4.0).
You also need to disable server side rendering for the pages that use my framework.
(it's using browser APIs that are not provided by SvelteKit on the server-side).

I added some notes on what is required in the docs here: https://github.com/perfect-things/ui/#usage-with-sveltekit
(I will update the docs & site soon)


Here's my PR: https://github.com/KoljaL/perfect-things-ui-issue/pull/1

**Comment by KoljaL** [comment]
Thanks for the quick reply.
I tried it now only briefly, but in the test-repo it works :-).

That SSR with your UI does not work, is really a pity.
Do you plan to enable this in the future?

**Comment by tborychowski** [comment]
No, I don't think so. 

A lot of my code relies on the browser APIs that is not available on the server side. 
This makes the components lightweight and performant (because they work with native APIs and not using fake abstractions) and I prefer to keep them like that. 
Maybe there are ways to convert them somehow, I don't know the SSR that well. I also don't like the concept. 
And because I don't need it at this time - I don't intend to invest in it. Sorry 🙂

**Comment by KoljaL** [comment]
Okay, I found a "solution", but I am not happy with it:

```js
<Button on:click={() => menu1.open(event)}>Open menu</Button>
```

Adding the parameter `event`to the `open()` function fix the issue, but I will get a warning, that the event-parameter is deprecated.

**Comment by tborychowski** [comment]
The event issue is a weird one. I suspect that sveltekit setup messes with the native browser events again ;-)
I'll have a look.

As for the SSR - what you suggested just wouldn't work.
It's not like the component has basic functionality (without browser APIs) and some extra functionality that requires browser's APIs. It's all connected and integrated, and inseparable.

Almost all components use `window` or `document` or similar and without that they just wouldn't work. There would be no interactivity.

**Comment by tborychowski** [comment]
Ok, so (I will look into some better error handling) but basically you need the event to be passed to the `menu.open` function, and you can do this in 2 ways:
```svelte
<Button on:click={menu1.open}>Open menu</Button>
<Button on:click={ev => menu1.open(ev)}>Open menu</Button>
```
