### ISSUE TITLE
Icons will not render

### ISSUE THREAD

**Issue by KoljaL** [perfect-things/ui#21]
It is a screenshot from this repo:
https://github.com/KoljaL/perfect-things-ui-issue

<img width="590" alt="grafik" src="https://user-images.githubusercontent.com/55852574/233636907-87a94434-e0f1-427f-9f84-c43d152d0ce3.png">

**Comment by tborychowski** [comment]
Thanks for the issue report. 
I just realised I don't have this documented 😉
SVGs need to be inlined by your bundler during the build process. Some bundlers do that by default, others may require a plugin. 
In Vite it would be sth like this:

https://vitejs.dev/guide/assets.html#importing-asset-as-string
(in which case I'd have to update them in my repo)


But let me think about that. Maybe I can improve that.

**Comment by KoljaL** [comment]
I already suspected something like that.

Unfortunately, my first attempt did not work:

```js
import Plus from '@perfectthings/ui/src/svg/plus.svg?raw';
```

**Comment by tborychowski** [comment]
ok. you can check out the v6.4.1 (just published). I removed the need to inline svg and added the ability to add custom icons :-)

**Comment by tborychowski** [comment]
Icons should render correctly now. 
Feel free to re-open if you have any issues with them still.
